### ISSUE TITLE
Running in production mode produces error

### ISSUE THREAD

**Issue by kuronosec** [LibreBlocksio/Libre-Blocks-Explorer#6]
According to the README documentation, running the block explorer in production mode involves the following command:

`pm2 start yarn --name "libreblocks" -- next start`

However I see the following error:
`0|libreblo | /usr/share/yarn/bin/yarn:2
0|libreblo | argv0=$(echo "$0" | sed -e 's,\\,/,g')
0|libreblo |         ^^^^
0|libreblo | 
0|libreblo | SyntaxError: missing ) after argument list
0|libreblo |     at Object.compileFunction (node:vm:360:18)
0|libreblo |     at wrapSafe (node:internal/modules/cjs/loader:1126:15)
0|libreblo |     at Module._compile (node:internal/modules/cjs/loader:1162:27)
0|libreblo |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
0|libreblo |     at Module.load (node:internal/modules/cjs/loader:1076:32)
0|libreblo |     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
0|libreblo |     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
0|libreblo |     at Module._compile (node:internal/modules/cjs/loader:1198:14)
0|libreblo |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
0|libreblo |     at Module.load (node:internal/modules/cjs/loader:1076:32)`

OS: Debian 11
Yarn version: 1.22.19
npm version: 8.19.4

I have found a solution by adding `--interpreter bash` to the command line, since apparently yarn is being executed by nodejs instead of the OS shell command.

**Comment by LibreBlocksDev** [comment]
Hello,

Does your problem still persist? @kuronosec

**Comment by kuronosec** [comment]
Hi @LibreBlocksDev now I am using Debian 12 and it works fine there, let me see if I can test it back in Debian 11.
